### ISSUE TITLE
Bug: 모여런 방 생성 시 오전 00시 xx분 선택 불가

### ISSUE THREAD

**Issue by sjsjsj1246** [MoyeoRun/MoyeoRun_Web#55]
![image](https://user-images.githubusercontent.com/24623403/142325565-d296b7bf-0e6c-432c-9829-e700529e2d3b.png)

**Comment by Sangjun-man** [comment]
보통 오전 00시 오후 00시에  보자라고는 잘 표현하지 않는것 같아서

ex) 17일에서 18일로 넘어간다고 하면
오후 12시 -> 17일 24시, 18일 00시
오전 12시 -> 18일 오전 12시, 오후 00시

이렇게 의도하고 숫자 옵션을 설정했는데 

![image](https://user-images.githubusercontent.com/66112027/142361227-a4f71cb6-fa14-45ca-a943-a1535b026840.png)

배포화면에서 확인해보니 숫자가 바뀌어있네요


이전 사항이랑 지금 사항 비교해서 뭐가 더 나은지 얘기해보고 수정해야할 것 같습니다
